name: music
description: A cross-platform music app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  husky: ^0.1.4+2

flutter:
  uses-material-design: true
